# Generated by Django 2.1.7 on 2019-04-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('images', models.CharField(max_length=255)),
            ],
        ),
    ]
