# Generated by Django 2.1.7 on 2019-04-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0004_weathers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('commit', models.CharField(max_length=255)),
                ('shop', models.CharField(max_length=255)),
                ('icons', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
