# Generated by Django 2.1.7 on 2019-04-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0008_auto_20190418_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDPhone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('commit', models.CharField(max_length=255)),
                ('shop', models.CharField(max_length=255)),
                ('icons', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Phones',
        ),
    ]
